categories:
- InteractiveTools
description: RStudio with Bioconductor for interactive analysis
homepage_url: https://github.com/afgane/rstudio_bioconductor_it
name: rstudio_bioconductor_it
owner: enis
